config/routes.rb
Friends::Application.routes.draw do

  devise_for :users

  root :to => "home#index"
  match 'feed' => "home#feed", :as => :feed 
  match 'inbox' => "home#inbox", :as => :inbox
  match 'outbox' => "home#outbox", :as => :outbox
  match 'friends' => "home#friends", :as => :friends
  match 'notifications' => "home#notifications", :as => :notifications
  resources :users, :only => [:show,:index] do
    get 'search', :on => :collection 
    member do
      delete 'delete'
      post 'create_invite'
      get 'dialog'
    end
    resources :photo_albums
    resources :posts, :only => [:create]
    resources :photos, :only => [:index]
    resources :messages, :only => [:new,:create]
  end

  resources :photo_albums, :only => [] do
    resources :photos, :only => [:new,:create]
  end

  resources :photos, :except => [:new,:create,:index] do
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Photo"
    resources :comments,  :only => [:create], :commentable => "Photo"
  end

  resources :user_friendships, :only => [] do
    member do
      put 'accept'
      delete 'cancel'
    end  
  end

  resources :messages, :only => [:show] do
    put 'mark_to_delete', :on => :member
  end

  resources :posts, :except => [:new, :index,:create] do
    resources :comments, :only => [:create], :commentable => "Post"
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Post"
  end

  resources :comments, :only => [:update,:edit,:destroy] do
    member do
      put :toggle_like, :controller => :likes,
       :action => :toggle, :likeable => "Comment"
    end
  end

end

app/views/shared/_comment_form.html.erb
<%= form_for [@parent,@comment], :html => {:class => "form-horizontal"} do |f| %>
	<%= render 'shared/error_messages', :object => f.object %> 
	<div class="control-group">
 		<div class="controls">
 			<%= f.text_area :content, :class => "text_area" %>
 		</div>
	</div>
 	<div class="actions">
 		<%= f.submit "Submit comment", :class => "btn" %>
 	</div>
<% end %>

app/views/shared/_comment_notification.html.erb
<div class="row-fluid">
	<div class="span2">
		<%= image_tag item.user.avatar.url(:thumb) %>
	</div>
	<div class="span8">
		<%= link_to item.user.fname, user_path(item.user) %>
		<p> <%= item.notificable.content %> </p>
		<p><strong>in reply to your <%= link_to item.notificable.commentable_type.downcase, 
										item.notificable.commentable %>:</strong></p>
			<div class="well">
				<% if item.notificable.commentable_type == "Photo" %>
					<%= item.notificable.commentable.content.url(:thumb) %>
				<% else %>
					<%= item.notificable.commentable.content %>
				<% end %>	
			</div>
		<div class="form-actions">
			<strong><%= item.notificable.likes.count %> people liked this</strong>
  			<% if item.notificable.cant_like?(current_user.id) %>
    			<%= link_to toggle_like_comment_path(item.notificable), :method => :put, :class => 'btn' do %>
      				<i class="icon-thumbs-up"></i> 
      				Like
    			<% end %>
  			<% else %>
    			<%= link_to toggle_like_comment_path(item.notificable), :method => :put, :class => 'btn' do %>
      				<i class="icon-thumbs-down"></i> 
      				Dislike
    			<% end %>
  			<% end %>
		</div>	
	</div>
</div>

app/views/shared/_comments.html.erb
<div class="row-fluid">
  <div class="span12">
    <%= render :partial => 'shared/comment_form' %>
    <% unless @comments.blank? %>
      <h3>Comments:</h3>
      <%= render @comments %>
    <% else %>
      <p> No comments here </p> 
    <% end %>
  </div>
</div>    

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_friend.html.erb
<div class="row-fluid">
	<div class="span2">
		<%= image_tag friend.avatar.url(:thumb) %>
	</div>
	<div class="span8">
		<%= link_to friend.fname, user_path(friend) %>
	</div>
</div>

app/views/shared/_invite.html.erb
<div class="row-fluid">
	<div class="span2">
		<%= image_tag invite.user.avatar.url(:thumb) %>
	</div>
	<div class="span6">
		<%= link_to invite.user.fname, user_path(invite.user) %>
		<p>want to add you to friends</p>
		<div class="form-actions">
			<%= link_to("Accept invite", accept_user_friendship_path(invite), :method => :put,
				:class => "btn btn-primary") %> 
			<%= link_to("Cancel invite", cancel_user_friendship_path(invite), :method => :delete,
				:class => "btn btn-primary") %>
		</div>
	</div>
</div>

app/views/shared/_item.html.erb
<div class="row-fluid">
	<div class="span1">
		<%= image_tag item.user.avatar.url(:thumb) %>
	</div>
	<div class="span9">
	 	<blockquote>
	 		<%= link_to item do %>
	        	<p><%= item.content %></p>
	        	<%= image_tag item.photo.url if item.photo_file_name %>
	        <% end %>	
	        <%= link_to user_path(item.user) do %>
	          <small><%= item.user.fname %></small>
	        <% end %> 
	    </blockquote>
	    <div class="well">
	  		<strong><%= item.likes.count %> people liked this</strong> | 
	  		<strong>comments: <%= item.comments.size %></strong>          
		</div>
	</div>
</div>

app/views/shared/_like_notification.html.erb
<div class="row-fluid">
	<div class="span2">
		<%= image_tag item.user.avatar.url(:thumb) %>
	</div>
	<div class="span8">
		<%= link_to item.user.fname, user_path(item.user) %>
		<p><strong>liked your <%= link_to item.notificable.likeable_type.downcase, 
										item.notificable.likeable %>:</strong></p>
			<div class="well">
				<% if item.notificable.likeable_type == "Photo" %>
					<%= item.notificable.likeable.content.url(:thumb) %>
				<% else %>
					<%= item.notificable.likeable.content %>
				<% end %>	
			</div>	
	</div>
</div>

app/views/shared/_message_form.html.erb
<%= form_tag(user_messages_path(@user), :method => :post,
	 :html => {:class =>"form-horizontal"}) do %>
	<div class="control-group">
		<%= label_tag :content, "Write", :class => "control-label" %>
		<div class="controls">
			<%= text_area_tag :content, nil, :class => "text_area"  %>
		</div>		
	</div>
	<div class="actions">
      	<%= submit_tag "Send", :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_message_item.html.erb
<div class="row-fluid">
	<div class="span1">
		<%= image_tag item.user.avatar.url(:thumb) %> 
	</div>
	<div class="span7">
		<p><strong><%= link_to item.user.name, item.user %></strong></p>
		<div class="well">
			<%= item.content %>
		</div>
	</div>
</div>

app/views/shared/_message_notification.html.erb
<div class="row-fluid">
	<div class="span2">
		<%= image_tag item.user.avatar.url(:thumb) %>
	</div>
	<div class="span8">
		<%= link_to item.user.fname, user_path(item.user) %>
		<p><strong>send you message:</strong></p>
			<div class="well">
				<%= item.notificable.content %>
			</div>
			<div class="form-actions">
				<%= link_to "Go to dialog", dialog_user_path(item.user), :class => "btn" %>
			</div>	
	</div>
</div>

app/views/shared/_post_form.html.erb
<%= form_for [@user,@post],:html => {:class => "form-horizontal"} do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
 	<fieldset> 
 		<div class="control-group">
 			<%= f.label :content, :class => "control-label" %>
 			<div class="controls">
 				<%= f.text_area :content, :class => "text_area", :placeholder => "Type something…",
 				 :rows => 10, :cols => 40 %>
 			</div>	
 		</div>
  		<div class="control-group">
  			<%= f.label :photo, :class => "control-label" %>
  			<div class="controls">
   				<%= f.file_field :photo %>
   			</div>	
  		</div>
 		<div class="form-actions">
 			<%= f.submit "Submit", :class => "btn btn-primary" %>
 		</div>
	</fieldset> 
<% end %>

app/views/shared/_post_notification.html.erb
<div class="row-fluid">
	<div class="span2">
		<%= image_tag item.user.avatar.url(:thumb) %>
	</div>
	<div class="span8">
		<%= link_to item.user.fname, user_path(item.user) %>
		<p><strong>added post to your wall:</strong></p>
			<div class="well">
				<%= item.notificable.content %>
			</div>
			<div class="form-actions">
				<strong><%= item.notificable.likes.count %> people liked this</strong>
  				<% if item.notificable.cant_like?(current_user.id) %>
    				<%= link_to toggle_like_post_path(item.notificable), :method => :put, :class => 'btn' do %>
      					<i class="icon-thumbs-up"></i> 
      					Like
    				<% end %>
  				<% else %>
    				<%= link_to toggle_like_post_path(item.notificable), :method => :put, :class => 'btn' do %>
      					<i class="icon-thumbs-down"></i> 
      					Dislike
    				<% end %>
  				<% end %>
				<%= link_to "Go to post", item.notificable, :class => "btn" %>
			</div>	
	</div>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag("/users/search", :method => "get", 
	:html => {:class => "well form-search"}) do %>
  <%= text_field_tag(:search,nil,:class => "input-medium search-query") %>
  <%= submit_tag("Search",:class => "btn") %>
<% end %>