config/routes.rb
Friends::Application.routes.draw do

  devise_for :users

  root :to => "home#index"
  match 'feed' => "home#feed", :as => :feed 
  match 'inbox' => "home#inbox", :as => :inbox
  match 'outbox' => "home#outbox", :as => :outbox
  match 'friends' => "home#friends", :as => :friends
  match 'notifications' => "home#notifications", :as => :notifications
  resources :users, :only => [:show,:index] do
    get 'search', :on => :collection 
    member do
      delete 'delete'
      post 'create_invite'
      get 'dialog'
    end
    resources :photo_albums
    resources :posts, :only => [:create]
    resources :photos, :only => [:index]
    resources :messages, :only => [:new,:create]
  end

  resources :photo_albums, :only => [] do
    resources :photos, :only => [:new,:create]
  end

  resources :photos, :except => [:new,:create,:index] do
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Photo"
    resources :comments,  :only => [:create], :commentable => "Photo"
  end

  resources :user_friendships, :only => [] do
    member do
      put 'accept'
      delete 'cancel'
    end  
  end

  resources :messages, :only => [:show] do
    put 'mark_to_delete', :on => :member
  end

  resources :posts, :except => [:new, :index,:create] do
    resources :comments, :only => [:create], :commentable => "Post"
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Post"
  end

  resources :comments, :only => [:update,:edit,:destroy] do
    member do
      put :toggle_like, :controller => :likes,
       :action => :toggle, :likeable => "Comment"
    end
  end

end

app/models/photo_album.rb
class PhotoAlbum < ActiveRecord::Base
  attr_accessible :name, :description

  validates :name, :presence => true

  belongs_to :user
  has_many :photos, :dependent => :destroy
end

app/controllers/photo_albums_controller.rb
class PhotoAlbumsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :check_user, :except => [:show,:index]


	def index
		@user = User.find(params[:user_id])
		@photo_albums = @user.photo_albums
	end

	def show
		@photo_album = PhotoAlbum.find(params[:id])
		@photos = @photo_album.photos
	end

	def create
		@photo_album = @user.photo_albums.build(params[:photo_album])
		if @photo_album.save
			redirect_to user_photo_album_path(@user,@photo_album)
		else
			render 'form'
		end
	end

	def new
		@photo_album = @user.photo_albums.new 
		render 'form'
	end

	def edit
		@photo_album = PhotoAlbum.find(params[:id])
		render 'form'
	end

	def update
		@photo_album = PhotoAlbum.find(params[:id])
		if @photo_album.save
			redirect_to user_photo_album_path(@user,@photo_album)
		else
			render 'form'
		end	
	end

	def destroy
		@photo_album = PhotoAlbum.find(params[:id])
		@photo_album.destroy
		redirect_to user_photo_albums_path(@user)
	end

	private

	def check_user
		@user = User.find(params[:user_id])
		redirect_to root_path if current_user != @user
	end
end

app/helpers/photo_albums_helper.rb
module PhotoAlbumsHelper
end

app/views/photo_albums/form.html.erb
<%= form_for [@user,@photo_album], :html => {:class => "forn-horizontal"} do |f| %>
	<div class="control-group">
		<%= f.label :name, :class => "control-label" %>
		<div class="controls">
  			<%= f.text_field :name, :class => "text_field" %>
  		</div>
	</div>
	<div class="control-group">
		<%= f.label :description, :class => "control-label" %>
		<div class="controls">
  			<%= f.text_area :description, :class => "text_area" %>
  		</div>	
	</div>
   <div><%= f.submit "Commit", :class => "btn btn-primary" %></div>
<% end %>

app/views/photo_albums/index.html.erb
<div class="form-actions">
	<% if @user == current_user %>
		<%= link_to "New album", new_user_photo_album_path(@user), :class => "btn btn-primary" %>
	<% end %>
	<%= link_to "All photos", user_photos_path(@user), :class => "btn" %>
</div>
<% unless @photo_albums.blank? %>
	<ul class="thumbnails">
	<% @photo_albums.each do |photo_album| %>
		<li class="span3">
		<div class="thumbnail">
			<%= link_to user_photo_album_path(@user,photo_album) do %>
			<% if photo_album.photos.any? %>
				<%= image_tag(photo_album.photos.last.content.url(:thumb)) %><br/>
			<% end %>
			<%= photo_album.name %>
			<% end %>
		</div>	
		</li>
	<% end %>
	</ul>
<% else %>
	<p> No albums here</p>	
<% end %>

app/views/photo_albums/show.html.erb
<% unless @photos.blank? %>
<ul class="thumbnails">
	<% @photos.each do |photo| %>
	<li class="span3">
	<div class="thumbnail">
	<%= link_to photo_path(photo) do %>
		<%= image_tag photo.content.url(:thumb) %>
	<% end %>
	</div>
	</li>
	<% end %>
</ul>
<% else %>
	<p> This album haven't any photos yet</p>
<% end %>
<% if @photo_album.user == current_user %>
	<div class="form-actions">
		<%= link_to "Add photo", new_photo_album_photo_path(@photo_album),:class => "btn" %> 
		<%= link_to "Edit album", edit_user_photo_album_path(@photo_album.user,@photo_album),
			:class => "btn" %> 
		<%= link_to "Delete album", [@photo_album.user,@photo_album], :method => :delete,
			:class => "btn btn-danger" %>
	</div>	
<% end %>