config/routes.rb
Friends::Application.routes.draw do

  devise_for :users

  root :to => "home#index"
  match 'feed' => "home#feed", :as => :feed 
  match 'inbox' => "home#inbox", :as => :inbox
  match 'outbox' => "home#outbox", :as => :outbox
  match 'friends' => "home#friends", :as => :friends
  match 'notifications' => "home#notifications", :as => :notifications
  resources :users, :only => [:show,:index] do
    get 'search', :on => :collection 
    member do
      delete 'delete'
      post 'create_invite'
      get 'dialog'
    end
    resources :photo_albums
    resources :posts, :only => [:create]
    resources :photos, :only => [:index]
    resources :messages, :only => [:new,:create]
  end

  resources :photo_albums, :only => [] do
    resources :photos, :only => [:new,:create]
  end

  resources :photos, :except => [:new,:create,:index] do
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Photo"
    resources :comments,  :only => [:create], :commentable => "Photo"
  end

  resources :user_friendships, :only => [] do
    member do
      put 'accept'
      delete 'cancel'
    end  
  end

  resources :messages, :only => [:show] do
    put 'mark_to_delete', :on => :member
  end

  resources :posts, :except => [:new, :index,:create] do
    resources :comments, :only => [:create], :commentable => "Post"
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Post"
  end

  resources :comments, :only => [:update,:edit,:destroy] do
    member do
      put :toggle_like, :controller => :likes,
       :action => :toggle, :likeable => "Comment"
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Likeable
  include Commentable
  attr_accessible :description, :content

  has_many :likes, :as => :likeable, :dependent => :destroy, :after_add => :notify_owner_about_like
  has_many :comments, :as => :commentable, :dependent => :destroy, :after_add => :notify_owner_about_comment

  belongs_to :user
  belongs_to :photo_album
  after_create :set_user

  has_attached_file :content, :styles => {:thumb => "100x100>" },
    :storage => :s3,
    :bucket => 'mogilevsky',
    :s3_credentials => {:access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET']}
  validates_attachment :content, :presence => true

  def set_user
  	User.find(photo_album.user).photos << self
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_filter :authenticate_user!
	before_filter :check_album, :only => [:new,:create]
	before_filter :check_user, :only => [:edit,:update,:destroy]

	def new
		@photo = @photo_album.photos.new
		render 'form'		 
	end

	def create
		@photo = @photo_album.photos.build(params[:photo])
		if @photo.save
			redirect_to photo_path(@photo)
		else
			render 'form'
		end
	end

	def toggle_like
		Photo.like(params[:id],current_user.id)
		redirect_to photo_path(params[:id])
	end

	def edit
		render 'form'
	end

	def update
		if @photo.update_attributes(params[:photo])
			redirect_to photo_path(@photo)
		else
			render 'form'
		end
	end

	def index
		@user = User.find(params[:user_id])
		@photos = @user.photos
	end

	def show
		@parent = @photo = Photo.find(params[:id])
		@comments = @photo.comments.includes(:user) 
		@comment = current_user.comments.new
	end

	def destroy
		@photo.destroy
		redirect_to user_photo_album_path(@photo.user,@photo.photo_album)
	end

	private

	def check_album
		@photo_album = PhotoAlbum.find(params[:photo_album_id])
		redirect_to root_path if current_user != @photo_album.user
	end

	def check_user
		@photo = Photo.find(params[:id])
		redirect_to root_path if current_user != @photo.user
	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/form.html.erb
<%= form_for [@photo_album,@photo], 
	:html => {:class => "form-horizontal"} do |f| %>
  	<div class="control-group">
  		<div class="controls">
  			<%= f.file_field :content, :class => "file_field" %>
  		</div>
	</div>
	<div class="control-group">
		<%= f.label :description, :class => "control-label" %><br />
		<div class="controls">
  			<%= f.text_area :description %>
  		</div>
	</div>
   <div><%= f.submit "Submit",:class => "btn" %></div>
<% end %>

app/views/photos/index.html.erb
<% unless @photos.blank? %> 
	<ul class="thumbnails">
	<% @photos.each do |photo| %>
		<li class="span3">
		<%= link_to photo_path(photo) do %>
			<%= image_tag photo.content.url(:thumb) %>
		<% end %>
		</li>
	<% end %>
	</ul>
<% else %>
	<p> No photos here </p>	
<% end %>	

app/views/photos/show.html.erb
<%- model_class = @photo.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<div class="row-fluid">
  <div class="span10">
        <p><%= image_tag @photo.content.url %></p>
        <p>added by: <%= link_to @photo.user.fname, user_path(@photo.user)%></p> 
  </div>
</div>
<div class="form-actions">
  <strong><%= @photo.likes.count %> people liked this</strong>
  <% if @photo.cant_like?(current_user.id) %>
    <%= link_to toggle_like_photo_path(@photo), :method => :put, :class => 'btn' do %>
      <i class="icon-thumbs-up"></i> 
      Like
    <% end %>
  <% else %>
    <%= link_to toggle_like_photo_path(@photo), :method => :put, :class => 'btn' do %>
      <i class="icon-thumbs-down"></i> 
      Dislike
    <% end %>
  <% end %> 
  <% if current_user == @photo.user %>            
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_photo_path(@photo), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                @photo, :method => 'delete',
                :confirm => t('.confirm',:default => t("helpers.links.confirm",:default => 'Are you sure?')),
                :class => 'btn btn-danger' %>
  <% end %>           
</div>
<%= render "shared/comments" %>