config/routes.rb
Friends::Application.routes.draw do

  devise_for :users

  root :to => "home#index"
  match 'feed' => "home#feed", :as => :feed 
  match 'inbox' => "home#inbox", :as => :inbox
  match 'outbox' => "home#outbox", :as => :outbox
  match 'friends' => "home#friends", :as => :friends
  match 'notifications' => "home#notifications", :as => :notifications
  resources :users, :only => [:show,:index] do
    get 'search', :on => :collection 
    member do
      delete 'delete'
      post 'create_invite'
      get 'dialog'
    end
    resources :photo_albums
    resources :posts, :only => [:create]
    resources :photos, :only => [:index]
    resources :messages, :only => [:new,:create]
  end

  resources :photo_albums, :only => [] do
    resources :photos, :only => [:new,:create]
  end

  resources :photos, :except => [:new,:create,:index] do
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Photo"
    resources :comments,  :only => [:create], :commentable => "Photo"
  end

  resources :user_friendships, :only => [] do
    member do
      put 'accept'
      delete 'cancel'
    end  
  end

  resources :messages, :only => [:show] do
    put 'mark_to_delete', :on => :member
  end

  resources :posts, :except => [:new, :index,:create] do
    resources :comments, :only => [:create], :commentable => "Post"
    put :toggle_like, :on => :member, :controller => :likes,
     :action => :toggle, :likeable => "Post"
  end

  resources :comments, :only => [:update,:edit,:destroy] do
    member do
      put :toggle_like, :controller => :likes,
       :action => :toggle, :likeable => "Comment"
    end
  end

end

app/views/layouts/_header.html.erb
<li><%= link_to "Home", root_path  %></li>
<% if signed_in? %>
  <li><%= link_to "Profile", user_path(current_user) %></li>
  <% unless @notification_count.zero? %>
  <li><%= link_to("Notifications (#{@notification_count})",notifications_path) %></li>
  <% end %>
  <%= raw('<li>'+get_friends_link(@invite_count)+'</li>') %>
  <li><%= link_to "Photos", user_photo_albums_path(current_user) %></li>
  <li><%= link_to "People", users_path %></li>
  <li><%= link_to "Inbox", inbox_path %></li>
  <li><%= link_to "Outbox", outbox_path %></li>
  <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
<% else %>
  <li><%= link_to "Sign in", new_user_session_path %></li>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Friends" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Friends</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <%= render 'layouts/header' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="content">
        <div class="row-fluid">
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Friends</h3>
                <ul class="nav nav-list">
                  <%= render 'layouts/header' %>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
            <div class="span9">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; trulala 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path  %></li>
      <% if signed_in? %>
        <li><%= link_to "Profile", profile_path %></li>
        <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </nav>
</header>